name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: git crypt unlock
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Remove lib/l10n directory
        run: rm -rf lib/l10n/*.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Regenerate the localization files
        run: flutter gen-l10n

      - name: generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze --fatal-infos

      - name: Run custom lints
        run: dart run custom_lint --fatal-infos

      - name: Flutter tests
        run: flutter test
